language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run build
deploy:
  provider: surge
  skip_cleanup: true
  domain: ovpv-live-stocks-app.surge.sh
  project: ./build/
on:
  branch: develop
